// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtXONjv3JdW8B_xrxxTJPudXXms6SZ6mU',
    appId: '1:455340459288:web:88b9abdfcf888c738e8a6d',
    messagingSenderId: '455340459288',
    projectId: 'lumina-stock',
    authDomain: 'lumina-stock.firebaseapp.com',
    storageBucket: 'lumina-stock.firebasestorage.app',
    measurementId: 'G-9M369DQ3ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCTc61UlYpC3IXIXuWXXX3KRAqog2Mb74',
    appId: '1:455340459288:android:057593f1b29deca48e8a6d',
    messagingSenderId: '455340459288',
    projectId: 'lumina-stock',
    storageBucket: 'lumina-stock.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs9VUkJwWdaP-OE10-4QY4ZX6EkNOjsGk',
    appId: '1:455340459288:ios:5947781c3cfdf2428e8a6d',
    messagingSenderId: '455340459288',
    projectId: 'lumina-stock',
    storageBucket: 'lumina-stock.firebasestorage.app',
    iosClientId: '455340459288-03529p6b2061qvcrv5ddmvdughajud0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.luminaStock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs9VUkJwWdaP-OE10-4QY4ZX6EkNOjsGk',
    appId: '1:455340459288:ios:5947781c3cfdf2428e8a6d',
    messagingSenderId: '455340459288',
    projectId: 'lumina-stock',
    storageBucket: 'lumina-stock.firebasestorage.app',
    iosClientId: '455340459288-03529p6b2061qvcrv5ddmvdughajud0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.luminaStock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtXONjv3JdW8B_xrxxTJPudXXms6SZ6mU',
    appId: '1:455340459288:web:3fdcb212a242157b8e8a6d',
    messagingSenderId: '455340459288',
    projectId: 'lumina-stock',
    authDomain: 'lumina-stock.firebaseapp.com',
    storageBucket: 'lumina-stock.firebasestorage.app',
    measurementId: 'G-XDDB4M1Y0W',
  );
}
